FROM mysql:8.0
# Copy our custom SQL file to /docker-entrypoint-initdb.d folder
# COPY ./create_second_db.sql /docker-entrypoint-initdb.d/create_second_db.sql
# Đối với Mysql, ta chỉ cần pull image từ docker hub về 